### ISSUE TITLE
Add MongoDB BSON codec

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-schema#543]
Add a codec for MongoDB BSON. It should be self-contained and not add new dependencies. Added as a top-level project, similar to `avro` support.

**Comment by senia-psm** [comment]
Zero new dependencies is quite hard since `org.bson` is quite java-style.

But we have `zio-bson` library in one of `ziverge` projects and we should be able to publish it. There is magnolia-based derivation and I've implemented `zio-schema` derivation already. I'm waiting for confirmation from @runtologist to publish it.

**Comment by runtologist** [comment]
@senia-psm  Let's do this!
