### ISSUE TITLE
ZIO Schema doesn't differentiate `Either[L, R]` from fallback semantics

### ISSUE THREAD

**Issue by gnp** [zio/zio-schema#584]
ZIO Schema has both support for a member of type `Either[L, R]` via `Schema.either` and for something that appears to be intended for fallback via `Schema.orElseEither`, but the latter just encodes to the same thing as the former. And, when you go to use it, you do not actually get fallback semantics. For example, you cannot use it to decode JSON "`[42, "43"]`" to something that can either decode from `Long` or `String`.

This is demonstrated in this Scastie: https://scastie.scala-lang.org/gnp/078lqgCNRjuNBwvnOPyWFg/10

**Comment by jdegoes** [comment]
/bounty $350

This addition to ZIO Schema would be a true fallback, which will encode properly, and attempt decode left first, followed by right if that fails. Because decoding either side could succeed, this implies that use of such a fallback operator will violate laws for union data that is encoded ambiguously.

Bounty for addition of the feature, updating existing codecs, and test suite.
